apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # labels of deployment resource
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: geethaprudhvi/app1:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector: #labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #pod port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  annotations:
    # ALB Ingress controller annotation
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:340495553266:certificate/622ef78b-2412-44ef-a0a4-a3c938c92d2d
    alb.ingress.kubernetes.io/group.name: "expense-group"
    #ingress class annotation
  spec:
    ingressClassName: alb
    rules:
    - host: "app1.kambalas.shop"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
           service:
             name: app1
             port:
               number: 80